# Generated by Django 3.0.5 on 2020-07-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
