# Generated by Django 3.0.5 on 2020-07-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200714_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
