# Generated by Django 3.0.5 on 2020-09-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('email', models.TextField(blank=True, max_length=50)),
                ('phone', models.TextField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
